# Generated by Django 5.2.14 on 2026-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('DETECTION', 'Detection Engine'), ('RESPONSE', 'Response Orchestration'), ('NETWORK', 'Network Settings'), ('RETENTION', 'Data Retention'), ('ALERTING', 'Alerting & Notifications')], default='DETECTION', max_length=20)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
