# Generated by Django 5.2.14 on 2026-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrecord',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
