# Generated by Django 5.2.14 on 2026-05-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MONITOR', 'Monitor'), ('CHALLENGE', 'Challenge'), ('THROTTLE', 'Throttle'), ('REDIRECT', 'Redirect'), ('BLOCK', 'Block'), ('ISOLATE', 'Isolate')], max_length=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('explanation', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.incident')),
            ],
        ),
    ]
